apiVersion: v1
kind: Service
metadata:
   name: db
   labels:
      name: db-service
      app: demo-votingapp-pod
spec:
   ports:
     - port: 5432
       targetport: 5432
   selector:
      name: postgres-pod
      app: demo-votingapp-pod   
   
