apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
       name: postgres-pod
       app: demo-votingapp-pod
  template:
     metadata:
       name: postgres-pod
       labels:
         name: postgres-pod
         app: demo-votingapp-pod
     spec:
         containers:
          - name: postgres-pod
            image: postgres:9.4
            ports: 
             containerPort: 5432 
