apiVersion: v1
kind: Service
metadata:
   name: redis
   labels:
      name: redis-service
      app: demo-votingapp-pod
spec:
   ports:
     - port: 6379
       targetport: 6379
   selector:
      name: redis-pod
      app: demo-votingapp-pod   
   
