apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: demo-votingapp-pod
  template:
     metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: demo-votingapp-pod
  spec:
     containers:
      - name: redis-pod
        image: redis:latest
        ports: 
         containerPort: 6379 